# Generated by Django 2.2.7 on 2019-12-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.jamesvillas.co.uk/images/jvh/holiday-destinations/resort/food-placeholder.jpg', max_length=500),
        ),
    ]
